name: Check PR

on: [pull_request,push]

jobs:
  # Lint changed templates.
  xlint:
    name: Lint templates
    runs-on: ubuntu-18.04

    env:
      PATH: '/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/bin:/tmp/bin'
      XLINT: '1'
      LICENSE_LIST: common/travis/license.lst

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 200
      - run: common/travis/fetch_upstream.sh
      - run: common/travis/changed_templates.sh
      - run: common/travis/fetch-xtools.sh
      - run: common/travis/xlint.sh
